language: ruby
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - chromium-chromedriver
cache:
  bundler: true
rvm:
- 2.3.5
- 2.4.2
- 2.5.0
before_install:
- openssl aes-256-cbc -K $encrypted_6662e8fa5891_key -iv $encrypted_6662e8fa5891_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- gem install bundler
before_script:
- bundle exec rake alchemy:spec:prepare
- export PATH=$PATH:/usr/lib/chromium-browser/
script: bundle exec rspec
after_success: bundle exec codeclimate-test-reporter
env:
- DB=mysql
- DB=postgresql
notifications:
  slack:
    secure: QzOFw1Ph69pzwWBFgtIVkOnjbcRxB9HPRQ+RYjK+2tg+fsbiTJ+wYgHcZL49tPYcLAls4kymkFWzWBF3PCAXJMfKgUCqXzdQ2FuJC/JoVRTLll4wDnZFPG33jsm5tVznmycZ3ma4+ZWfJQ+C+elEBOba6v1kG9eGIy6sH2cvXfE=
