/* eslint no-console:0 */
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.
//
// To reference this file, add <%= javascript_pack_tag 'alchemy/admin' %> to the appropriate
// layout file, like app/views/layouts/alchemy/admin.html.erb

require('jquery')
require('jquery-ujs')
require('turbolinks')
require('webpack-jquery-ui/fade-effect')
require('webpack-jquery-ui/draggable')
require('webpack-jquery-ui/sortable')
require('webpack-jquery-ui/tabs')
require('tinymce/tinymce')
require('tinymce/plugins/anchor')
require('tinymce/plugins/autoresize')
require('tinymce/plugins/charmap')
require('tinymce/plugins/code')
require('tinymce/plugins/directionality')
require('tinymce/plugins/fullscreen')
require('tinymce/plugins/hr')
require('tinymce/plugins/link')
require('tinymce/plugins/lists')
require('tinymce/plugins/paste')
require('tinymce/plugins/tabfocus')
require('tinymce/plugins/table')
require('tinymce/themes/modern')
require('jquery-datetimepicker')
require('jquery_plugins/jquery.Jcrop.min')
require('jquery_plugins/jquery.scrollTo.min')
require('jquery_plugins/jquery.ui.nestedSortable')
require('jquery_plugins/jquery.ui.tabspaging')
require('clipboard')
require('keymaster')
require('requestAnimationFrame')
require('select2')
require('alchemy/templates')
require('alchemy/alchemy.base.js.coffee')
require('alchemy/alchemy.autocomplete.js.coffee')
require('alchemy/alchemy.browser.js.coffee')
require('alchemy/alchemy.buttons.js.coffee')
require('alchemy/alchemy.dialog.js.coffee')
require('alchemy/alchemy.char_counter.js.coffee')
require('alchemy/alchemy.confirm_dialog.js.coffee')
require('alchemy/alchemy.datepicker.js.coffee')
require('alchemy/alchemy.dirty.js.coffee')
require('alchemy/alchemy.dragndrop.js.coffee')
require('alchemy/alchemy.element_editors.js.coffee')
require('alchemy/alchemy.elements_window.js.coffee')
require('alchemy/alchemy.fixed_elements')
require('alchemy/alchemy.growler.js.coffee')
require('alchemy/alchemy.gui.js.coffee')
require('alchemy/alchemy.hotkeys.js.coffee')
require('alchemy/alchemy.i18n.js.coffee')
require('alchemy/alchemy.image_cropper.js.coffee')
require('alchemy/alchemy.image_overlay.coffee')
require('alchemy/alchemy.string_extension.js.coffee')
require('alchemy/alchemy.link_dialog.js.coffee')
require('alchemy/alchemy.list_filter.js.coffee')
require('alchemy/alchemy.initializer.js.coffee')
require('alchemy/alchemy.page_sorter')
require('alchemy/alchemy.uploader.js.coffee')
require('alchemy/alchemy.preview_window.js.coffee')
require('alchemy/alchemy.sitemap.js.coffee')
require('alchemy/alchemy.spinner')
require('alchemy/alchemy.tinymce.js.coffee')
require('alchemy/alchemy.tooltips.coffee')
require('alchemy/alchemy.translations.js.coffee')
require('alchemy/alchemy.trash_window.js.coffee')
